/**
 * 15 fictional ClinicCare doctors.
 *
 * Every name, biography and credential here is invented for demonstration
 * purposes. None of it refers to a real clinician or is taken from any
 * third-party directory.
 */
const doctors = [
  {
    name: 'Dr. Ananya Rao',
    email: 'ananya.rao@cliniccare.com',
    phone: '9800000101',
    specialtyName: 'General Health',
    qualification: 'MBBS, MD (General Medicine)',
    experience: 14,
    consultationFee: 700,
    languages: ['English', 'Hindi', 'Kannada'],
    expertise: ['Preventive health checks', 'Fever management', 'Chronic disease review', 'Thyroid disorders'],
    bio: 'Ananya focuses on everyday adult medicine, from seasonal infections to long-term condition reviews. She believes most good outcomes start with an unhurried conversation and a clear explanation of what happens next.',
    rating: 4.8,
    slotDuration: 30,
  },
  {
    name: 'Dr. Rohan Mehta',
    email: 'rohan.mehta@cliniccare.com',
    phone: '9800000102',
    specialtyName: 'Heart Health',
    qualification: 'MBBS, MD, DM (Cardiology)',
    experience: 18,
    consultationFee: 1400,
    languages: ['English', 'Hindi', 'Gujarati'],
    expertise: ['Hypertension', 'Cholesterol management', 'Heart failure care', 'Preventive cardiology'],
    bio: 'Rohan works with patients managing blood pressure, cholesterol and long-term heart conditions. Much of his practice is preventive — helping people understand their numbers before they become a problem.',
    rating: 4.9,
    slotDuration: 30,
  },
  {
    name: 'Dr. Meera Krishnan',
    email: 'meera.krishnan@cliniccare.com',
    phone: '9800000103',
    specialtyName: 'Child Care',
    qualification: 'MBBS, MD (Paediatrics)',
    experience: 11,
    consultationFee: 800,
    languages: ['English', 'Tamil', 'Malayalam'],
    expertise: ['Newborn care', 'Vaccination schedules', 'Growth and development', 'Childhood allergies'],
    bio: 'Meera looks after children from their first days through adolescence. She spends as much time reassuring parents as treating patients, and keeps vaccination planning simple and predictable.',
    rating: 4.9,
    slotDuration: 20,
  },
  {
    name: 'Dr. Arjun Nair',
    email: 'arjun.nair@cliniccare.com',
    phone: '9800000104',
    specialtyName: 'Bone and Joint Health',
    qualification: 'MBBS, MS (Orthopaedics)',
    experience: 16,
    consultationFee: 1000,
    languages: ['English', 'Hindi', 'Malayalam'],
    expertise: ['Sports injuries', 'Arthritis care', 'Back and neck pain', 'Joint replacement follow-up'],
    bio: 'Arjun treats bone and joint problems with a strong bias toward conservative management first. He works closely with physiotherapists and only recommends surgery when the alternatives have genuinely been exhausted.',
    rating: 4.7,
    slotDuration: 30,
  },
  {
    name: 'Dr. Priya Deshmukh',
    email: 'priya.deshmukh@cliniccare.com',
    phone: '9800000105',
    specialtyName: "Women's Health",
    qualification: 'MBBS, MS (Obstetrics & Gynaecology)',
    experience: 13,
    consultationFee: 950,
    languages: ['English', 'Hindi', 'Marathi'],
    expertise: ['PCOS management', 'Pregnancy care', 'Menstrual health', 'Menopause support'],
    bio: 'Priya provides gynaecological care across every life stage. She has a particular interest in PCOS and in making sure patients leave with a plan they actually understand and can follow.',
    rating: 4.8,
    slotDuration: 30,
  },
  {
    name: 'Dr. Kabir Sethi',
    email: 'kabir.sethi@cliniccare.com',
    phone: '9800000106',
    specialtyName: 'Skin and Hair Health',
    qualification: 'MBBS, MD (Dermatology)',
    experience: 9,
    consultationFee: 850,
    languages: ['English', 'Hindi', 'Punjabi'],
    expertise: ['Acne treatment', 'Hair loss', 'Eczema and psoriasis', 'Pigmentation'],
    bio: 'Kabir treats skin and hair conditions with evidence-led, realistic plans. He is candid about what treatments can and cannot achieve, and about how long results genuinely take.',
    rating: 4.6,
    slotDuration: 20,
  },
  {
    name: 'Dr. Sneha Iyer',
    email: 'sneha.iyer@cliniccare.com',
    phone: '9800000107',
    specialtyName: 'Blood Sugar Health',
    qualification: 'MBBS, MD, DM (Endocrinology)',
    experience: 12,
    consultationFee: 1100,
    languages: ['English', 'Tamil', 'Hindi'],
    expertise: ['Type 2 diabetes', 'Thyroid disorders', 'Insulin management', 'Metabolic health'],
    bio: 'Sneha helps people manage diabetes and thyroid conditions over the long term. Her consultations focus on small, sustainable adjustments rather than sweeping changes that rarely last.',
    rating: 4.8,
    slotDuration: 30,
  },
  {
    name: 'Dr. Vikram Chauhan',
    email: 'vikram.chauhan@cliniccare.com',
    phone: '9800000108',
    specialtyName: 'Digestive and Liver Health',
    qualification: 'MBBS, MD, DM (Gastroenterology)',
    experience: 15,
    consultationFee: 1200,
    languages: ['English', 'Hindi'],
    expertise: ['Acid reflux', 'Irritable bowel syndrome', 'Fatty liver disease', 'Endoscopy assessment'],
    bio: 'Vikram sees patients with persistent digestive symptoms that have not settled with first-line treatment. He is methodical about ruling things out before settling on a diagnosis.',
    rating: 4.7,
    slotDuration: 30,
  },
  {
    name: 'Dr. Fatima Sheikh',
    email: 'fatima.sheikh@cliniccare.com',
    phone: '9800000109',
    specialtyName: 'Eye Care',
    qualification: 'MBBS, MS (Ophthalmology)',
    experience: 10,
    consultationFee: 750,
    languages: ['English', 'Hindi', 'Urdu'],
    expertise: ['Vision correction', 'Dry eye syndrome', 'Cataract assessment', 'Glaucoma screening'],
    bio: 'Fatima covers routine eye examinations through to the assessment of cataracts and glaucoma. She is a strong advocate for regular screening in patients with diabetes.',
    rating: 4.7,
    slotDuration: 20,
  },
  {
    name: 'Dr. Sameer Kulkarni',
    email: 'sameer.kulkarni@cliniccare.com',
    phone: '9800000110',
    specialtyName: 'ENT',
    qualification: 'MBBS, MS (ENT)',
    experience: 12,
    consultationFee: 800,
    languages: ['English', 'Hindi', 'Marathi'],
    expertise: ['Chronic sinusitis', 'Hearing assessment', 'Tonsillitis', 'Vertigo management'],
    bio: 'Sameer treats ear, nose and throat conditions in both adults and children. He has a particular interest in chronic sinus problems that have not responded to repeated antibiotic courses.',
    rating: 4.6,
    slotDuration: 20,
  },
  {
    name: 'Dr. Neha Bansal',
    email: 'neha.bansal@cliniccare.com',
    phone: '9800000111',
    specialtyName: 'Breathing and Lung Health',
    qualification: 'MBBS, MD (Pulmonary Medicine)',
    experience: 14,
    consultationFee: 1000,
    languages: ['English', 'Hindi', 'Punjabi'],
    expertise: ['Asthma control', 'COPD management', 'Chronic cough', 'Sleep apnoea'],
    bio: 'Neha works with patients whose breathing limits what they can do day to day. Getting inhaler technique right is, in her experience, one of the most under-rated wins in respiratory care.',
    rating: 4.8,
    slotDuration: 30,
  },
  {
    name: 'Dr. Aditya Verma',
    email: 'aditya.verma@cliniccare.com',
    phone: '9800000112',
    specialtyName: 'Kidney Care',
    qualification: 'MBBS, MD, DM (Nephrology)',
    experience: 17,
    consultationFee: 1300,
    languages: ['English', 'Hindi', 'Bengali'],
    expertise: ['Chronic kidney disease', 'Kidney stones', 'Dialysis planning', 'Blood pressure and kidneys'],
    bio: 'Aditya supports patients through every stage of kidney disease, with an emphasis on slowing progression early. He works closely with cardiology and endocrinology colleagues on shared cases.',
    rating: 4.7,
    slotDuration: 30,
  },
  {
    name: 'Dr. Ritu Malhotra',
    email: 'ritu.malhotra@cliniccare.com',
    phone: '9800000113',
    specialtyName: 'Dental Health',
    qualification: 'BDS, MDS (Conservative Dentistry)',
    experience: 8,
    consultationFee: 600,
    languages: ['English', 'Hindi'],
    expertise: ['Root canal treatment', 'Gum disease', 'Dental restorations', 'Preventive dentistry'],
    bio: 'Ritu focuses on preserving natural teeth wherever possible. She has built much of her practice around patients who have avoided dental care because of anxiety.',
    rating: 4.6,
    slotDuration: 30,
  },
  {
    name: 'Dr. Harish Pillai',
    email: 'harish.pillai@cliniccare.com',
    phone: '9800000114',
    specialtyName: 'Elder Care',
    qualification: 'MBBS, MD (Geriatric Medicine)',
    experience: 20,
    consultationFee: 900,
    languages: ['English', 'Malayalam', 'Tamil', 'Hindi'],
    expertise: ['Falls prevention', 'Memory assessment', 'Medication review', 'Mobility and frailty'],
    bio: 'Harish looks after older adults managing several conditions at once. A good proportion of his work is simplifying medication lists that have grown over the years without ever being reviewed as a whole.',
    rating: 4.9,
    slotDuration: 45,
  },
  {
    name: 'Dr. Tanvi Joshi',
    email: 'tanvi.joshi@cliniccare.com',
    phone: '9800000115',
    specialtyName: 'Pain Management',
    qualification: 'MBBS, MD (Anaesthesiology), Fellowship in Pain Medicine',
    experience: 11,
    consultationFee: 1050,
    languages: ['English', 'Hindi', 'Marathi'],
    expertise: ['Chronic back pain', 'Migraine management', 'Neuropathic pain', 'Post-surgical pain'],
    bio: 'Tanvi treats pain that has persisted beyond normal healing time. Her approach combines medical treatment with physical rehabilitation, because in her experience neither works as well on its own.',
    rating: 4.7,
    slotDuration: 30,
  },
]

export default doctors
